.PHONY: clean help pii_check quality requirements selfcheck test upgrade validate

.DEFAULT_GOAL := help

help: ## display this help message
	@echo "Please use \`make <target>' where <target> is one of"
	@grep '^[a-zA-Z]' $(MAKEFILE_LIST) | sort | awk -F ':.*?## ' 'NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}'

all: requirements quality test

clean: ## remove generated byte code, coverage reports, and build artifacts
	find . -name '__pycache__' -exec rm -rf {} +
	find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	coverage erase
	rm -fr build/
	rm -fr dist/
	rm -fr *.egg-info

pii_check: ## check for PII annotations on all Django models
	uv run tox -e pii_check

requirements: ## install development environment requirements
	uv sync --group dev

quality:
	uv run tox -e quality

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."

test: ## run tests on every supported Python version
	uv run tox

upgrade: ## update python dependencies
	uv run --with edx-lint edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

validate: quality pii_check test ## run tests and quality checks
