[tox]
envlist = quality, django{42, 52}
requires = tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
setenv =
    DJANGO_SETTINGS_MODULE = settings
    PYTHONPATH = {toxinidir}
dependency_groups =
    django42: django42
    django52: test
allowlist_externals = make
commands =
    python -Wd -m pytest {posargs}
    coverage report -m
    coverage xml

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
allowlist_externals = make
commands =
    pycodestyle --config=.pep8 manage.py src/milestones settings.py
    pylint --rcfile=.pylintrc manage.py src/milestones settings.py
    make selfcheck

[testenv:pii_check]
runner = uv-venv-lock-runner
setenv =
    DJANGO_SETTINGS_MODULE = settings
dependency_groups = test
commands =
    code_annotations django_find_annotations --config_file .pii_annotations.yml --lint --report --coverage
